version: '3.1'

services:
  zoo1:
    image: bitnami/zookeeper:3.9.1
    restart: always
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zoo1:2888:3888 zoo2:2888:3888 zoo3:2888:3888
      - ZOO_RECONFIG_ENABLED=yes

  zoo2:
    image: bitnami/zookeeper:3.9.1
    restart: always
    ports:
      - 2182:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zoo1:2888:3888 zoo2:2888:3888 zoo3:2888:3888
      - ZOO_RECONFIG_ENABLED=yes

  zoo3:
    image: bitnami/zookeeper:3.9.1
    restart: always
    ports:
      - 2183:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zoo1:2888:3888 zoo2:2888:3888 zoo3:2888:3888
      - ZOO_RECONFIG_ENABLED=yes

  broker1:
    image: bitnami/kafka:3.3.2
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
  # broker2: 
  #   image: bitnami/kafka:3.3.2
  #   restart: always
  #   ports:
  #     - 9093:9092
  #   environment:
  #     - KAFKA_CFG_NODE_ID=2
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #
  # broker3: 
  #   image: bitnami/kafka:3.3.2
  #   restart: always
  #   ports:
  #     - 9094:9092
  #   environment:
  #     - KAFKA_CFG_NODE_ID=3
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
        #
  # producer:
  #   image: producer:1.0
  #   depends_on:
  #    - broker1
  #
  # consumer:
  #   image: consumer:1.0
  #   depends_on:
  #     - producer
  # network:
  #   image: nicolaka/netshoot
  #   hostname: network
  #   stdin_open: true
  #   tty: true
